from aiosqlite import Connection, Row

class UsersQueriesMixin:
    async def create_new_user(self, conn: Connection, login: str, name: str) -> int: ...
    async def check_login_availability(self, conn: Connection, login: str) -> bool: ...

class ItemsQueriesMixin:
    async def create_new_item(self, conn: Connection, user_id: int, title: str, description: str, completed: bool) -> int: ...
    async def get_all_items(self, conn: Connection) -> list[Row]: ...
    async def get_user_items(self, conn: Connection, login: str) -> list[Row]: ...
    async def check_if_item_exists(self, conn: Connection, item_id: int) -> bool: ...
    async def get_item(self, conn: Connection, item_id: int) -> Row: ...
    async def update_item(self, conn: Connection, item_id: int, user_id: int, title: str, description: str, completed: bool) -> None: ...
    async def delete_item(self, conn: Connection, item_id: int) -> None: ...
    async def get_item_creator(self, conn: Connection, item_id: int) -> int: ...

class SchemaQueriesMixin:
    async def create_table_users(self, conn: Connection) -> None: ...
    async def create_table_items(self, conn: Connection) -> None: ...

class Queries(
    UsersQueriesMixin,
    ItemsQueriesMixin,
    SchemaQueriesMixin
): ...

queries: Queries
